---
- name: restart-systemd-buildkite
  systemd:
    name: "buildkite-agent"
    state: restarted
  when: ansible_os_family == "Debian" and buildkite_agent_allow_service_startup[ansible_os_family]

- name: restart-windows-buildkite
  win_service:
    name: "buildkite-agent"
    state: restarted
  when: ansible_os_family == "Windows" and buildkite_agent_allow_service_startup[ansible_os_family]

- name: restart-darwin-buildkite
  command: /usr/local/bin/brew services restart buildkite/buildkite/buildkite-agent {{ buildkite_agent_conf_dir[ansible_os_family] }}/homebrew.mxcl.buildkite-agent.plist
  when: ansible_os_family == "Darwin" and buildkite_agent_allow_service_startup[ansible_os_family]
